#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_LINE 1024
#define DEFAULT_BIO "Software Engineer | C/C++ Enthusiast"
#define DEFAULT_LOCATION ""
#define DEFAULT_WEBSITE ""

typedef struct {
    char name[256];
    char bio[MAX_LINE];
    char location[256];
    char website[MAX_LINE];
    int email_public;
} ProfileData;

static void trim_whitespace(char *str) {
    while (isspace((unsigned char)*str)) str++;
    if (*str == 0) return;
    
    char *end = str + strlen(str) - 1;
    while (end > str && isspace((unsigned char)*end)) end--;
    *(end + 1) = '\0';
}

static int validate_email(const char *email, size_t len) {
    if (!email || len == 0) return 0;
    
    const char *at = strchr(email, '@');
    if (!at || at - email < 2 || strlen(at + 1) < 2) return 0;
    
    for (size_t i = 0; i < len && !isspace((unsigned char)*email); i++) {
        unsigned char c = (unsigned char)email[i];
        if (!isalnum(c) && c != '.' && c != '_' && c != '-' && c != '+' && c != '%') {
            return 0;
        }
    }
    
    return 1;
}

static int validate_url(const char *url, size_t len) {
    if (!url || len == 0) return 1;
    
    const char *scheme = strstr(url, "://");
    if (!scheme) return 0;
    
    for (size_t i = 0; i < len && !isspace((unsigned char)*url); i++) {
        unsigned char c = (unsigned char)url[i];
        if (!isalnum(c) && c != '.' && c != '/' && c != '-' && c != '_' 
            && c != ':' && c != '+' && c != '~' && c != '@') {
            return 0;
        }
    }
    
    return 1;
}

static int read_profile_from_stdin(ProfileData *profile) {
    char line[MAX_LINE];
    int i = 0, j = 0;
    
    memset(profile, 0, sizeof(*profile));
    
    while (fgets(line, MAX_LINE, stdin)) {
        trim_whitespace(line);
        
        if (i == 0 && strncmp(line, "name:", 5) == 0) {
            strncpy(profile->name, line + 5, sizeof(profile->name) - 1);
            i++;
            continue;
        }
        
        if (i == 1 && strncmp(line, "bio:", 4) == 0) {
            strncpy(profile->bio, line + 4, sizeof(profile->bio) - 1);
            i++;
            continue;
        }
        
        if (i == 2 && strncmp(line, "location:", 9) == 0) {
            strncpy(profile->location, line + 9, sizeof(profile->location) - 1);
            i++;
            continue;
        }
        
        if (i == 3 && strncmp(line, "website:", 8) == 0) {
            strncpy(profile->website, line + 8, sizeof(profile->website) - 1);
            i++;
            continue;
        }
        
        if (i == 4 && strncmp(line, "email_public:", 13) == 0) {
            profile->email_public = atoi(line + 13);
            i++;
            continue;
        }
    }
    
    return 1;
}

static int write_yaml_profile(FILE *out, const ProfileData *profile) {
    fprintf(out, "# GitHub Profile Configuration\n");
    fprintf(out, "# Generated by cognis-digital profile-generator\n");
    fprintf(out, "\n");
    fprintf(out, "name: %s\n", profile->name ? profile->name : "");
    fprintf(out, "bio: \"%s\"\n", profile->bio ? profile->bio : DEFAULT_BIO);
    fprintf(out, "location: %s\n", profile->location ? profile->location : DEFAULT_LOCATION);
    fprintf(out, "website: %s\n", profile->website ? profile->website : DEFAULT_WEBSITE);
    fprintf(out, "email_public: %d\n", profile->email_public ? 1 : 0);
    
    return 0;
}

static int write_json_profile(FILE *out, const ProfileData *profile) {
    fprintf(out, "{\n");
    fprintf(out, "  \"name\": \"%s\",\n", 
            profile->name ? profile->name : "");
    fprintf(out, "  \"bio\": \"%s\",\n", 
            profile->bio ? profile->bio : DEFAULT_BIO);
    fprintf(out, "  \"location\": \"%s\",\n", 
            profile->location ? profile->location : DEFAULT_LOCATION);
    fprintf(out, "  \"website\": \"%s\",\n", 
            profile->website ? profile->website : DEFAULT_WEBSITE);
    fprintf(out, "  \"email_public\": %d\n", profile->email_public ? 1 : 0);
    fprintf(out, "}\n");
    
    return 0;
}

static int write_markdown_profile(FILE *out, const ProfileData *profile) {
    fprintf(out, "# %s\n", profile->name ? profile->name : "");
    fprintf(out, "\n## About\n");
    fprintf(out, "%s\n", profile->bio ? profile->bio : DEFAULT_BIO);
    fprintf(out, "\n## Contact\n");
    
    if (profile->email_public) {
        fprintf(out, "- Email: (public)\n");
    } else {
        fprintf(out, "- Email: (private)\n");
    }
    
    if (strlen(profile->location)) {
        fprintf(out, "- Location: %s\n", profile->location);
    }
    
    if (strlen(profile->website)) {
        fprintf(out, "- Website: <%s>\n", profile->website);
    }
    
    return 0;
}

static int generate_profile(const ProfileData *profile, 
                           const char *output_file,
                           const char *format) {
    FILE *out = fopen(output_file, "w");
    if (!out) {
        fprintf(stderr, "Error: Cannot open output file '%s'\n", output_file);
        return -1;
    }
    
    int result = 0;
    
    if (strcmp(format, "yaml") == 0 || strcmp(format, "yml") == 0) {
        write_yaml_profile(out, profile);
    } else if (strcmp(format, "json") == 0) {
        write_json_profile(out, profile);
    } else if (strcmp(format, "markdown") == 0 || 
               strcmp(format, "md") == 0) {
        write_markdown_profile(out, profile);
    } else {
        fprintf(stderr, "Error: Unknown format '%s'\n", format);
        fclose(out);
        return -1;
    }
    
    fclose(out);
    printf("Profile written to: %s\n", output_file);
    return 0;
}

static void print_usage(const char *prog) {
    fprintf(stderr, "Usage: %s [options]\n", prog);
    fprintf(stderr, "\nOptions:\n");
    fprintf(stderr, "  -i <file>   Read profile from file\n");
    fprintf(stderr, "  -o <file>   Output file (default: .github/profile.yaml)\n");
    fprintf(stderr, "  -f <fmt>    Output format: yaml|json|markdown (default: yaml)\n");
    fprintf(stderr, "  --stdin     Read profile from stdin\n");
    fprintf(stderr, "  --demo      Run demo with sample data\n");
    fprintf(stderr, "\nExample:\n");
    fprintf(stderr, "  %s -i config.yaml -o .github/profile.json -f json\n", prog);
}

static int run_demo(const ProfileData *profile) {
    printf("=== COGNIS-DIGITAL PROFILE GENERATOR ===\n\n");
    
    // Demo: Generate all formats to stdout
    printf("--- YAML Output ---\n");
    write_yaml_profile(stdout, profile);
    
    printf("\n--- JSON Output ---\n");
    write_json_profile(stdout, profile);
    
    printf("\n--- Markdown Output ---\n");
    write_markdown_profile(stdout, profile);
    
    return 0;
}

int main(int argc, char *argv[]) {
    ProfileData profile = {0};
    const char *output_file = ".github/profile.yaml";
    const char *format = "yaml";
    int read_from_stdin = 0;
    int run_demo_mode = 0;
    
    // Parse arguments
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--demo") == 0) {
            run_demo_mode = 1;
            continue;
        }
        
        if (argv[i][0] == '-') {
            if (strcmp(argv[i], "-i") == 0 && i + 1 < argc) {
                FILE *fin = fopen(argv[++i], "r");
                if (!fin) {
                    fprintf(stderr, "Error: Cannot open input file '%s'\n", argv[i]);
                    return 1;
                }
                
                while (fgets(profile.name, sizeof(profile.name), fin));
                fgets(profile.bio, sizeof(profile.bio), fin);
                fgets(profile.location, sizeof(profile.location), fin);
                fgets(profile.website, sizeof(profile.website), fin);
                fclose(fin);
            } else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
                output_file = argv[++i];
            } else if (strcmp(argv[i], "-f") == 0 && i + 1 < argc) {
                format = argv[++i];
            } else if (strcmp(argv[i], "--stdin") == 0) {
                read_from_stdin = 1;
            } else {
                fprintf(stderr, "Unknown option: %s\n", argv[i]);
                print_usage(argv[0]);
                return 1;
            }
        } else if (argv[i][0] != '-') {
            // Treat as direct input values for interactive mode
            strncpy(profile.name, argv[i], sizeof(profile.name) - 1);
        }
    }
    
    // Set defaults if not provided
    if (!profile.name[0]) strcpy(profile.name, "Developer");
    if (!profile.bio[0]) {
        strncpy(profile.bio, DEFAULT_BIO, sizeof(profile.bio) - 1);
    }
    if (!profile.location[0]) strcpy(profile.location, DEFAULT_LOCATION);
    if (!profile.website[0]) strcpy(profile.website, DEFAULT_WEBSITE);
    
    // Run demo mode if requested
    if (run_demo_mode) {
        return run_demo(&profile);
    }
    
    // Interactive mode: prompt for missing fields
    if (!read_from_stdin && !run_demo_mode) {
        printf("=== COGNIS-DIGITAL PROFILE INTERACTIVE MODE ===\n\n");
        
        char temp[MAX_LINE];
        
        if (strlen(profile.name) == 0 || profile.name[0] == 'D') {
            printf("Name: ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.name, temp, sizeof(profile.name) - 1);
            trim_whitespace(profile.name);
        }
        
        if (strlen(profile.bio) == 0 || profile.bio[0] == 'S') {
            printf("Bio: ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.bio, temp, sizeof(profile.bio) - 1);
            trim_whitespace(profile.bio);
        } else if (strlen(profile.bio) < 5) {
            printf("Bio (short): ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.bio, temp, sizeof(profile.bio) - 1);
            trim_whitespace(profile.bio);
        }
        
        if (strlen(profile.location) == 0 || profile.location[0] == 'L') {
            printf("Location: ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.location, temp, sizeof(profile.location) - 1);
            trim_whitespace(profile.location);
        } else if (strlen(profile.location) < 3) {
            printf("Location (short): ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.location, temp, sizeof(profile.location) - 1);
            trim_whitespace(profile.location);
        }
        
        if (strlen(profile.website) == 0 || profile.website[0] == 'W') {
            printf("Website: ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.website, temp, sizeof(profile.website) - 1);
            trim_whitespace(profile.website);
        } else if (strlen(profile.website) < 5) {
            printf("Website (short): ");
            fgets(temp, MAX_LINE, stdin);
            strncpy(profile.website, temp, sizeof(profile.website) - 1);
            trim_whitespace(profile.website);
        }
        
        profile.email_public = 0;
        printf("\nMake email public? [y/N]: ");
        char response[8];
        fgets(response, sizeof(response), stdin);
        if (response[0] == 'y' || response[0] == 'Y') {
            profile.email_public = 1;
        }
    }
    
    // Validate before writing
    int valid = 1;
    if (!strlen(profile.name)) valid = 0;
    if (strlen(profile.bio) < 3) valid = 0;
    
    printf("\n--- Summary ---\n");
    printf("Name: %s\n", profile.name);
    printf("Bio: %s\n", profile.bio);
    printf("Location: %s\n", profile.location);
    printf("Website: %s\n", profile.website);
    printf("Email Public: %s\n", profile.email_public ? "Yes" : "No");
    
    if (!valid) {
        fprintf(stderr, "\nWarning: Some fields may be incomplete.\n");
    } else {
        printf("\nReady to generate profile...\n");
    }
    
    // Generate output
    return generate_profile(&profile, output_file, format);
}